###################匯入模組###################
import pygame
import sys
import math
###################定義函式#################
def check_click(pos,x_min,y_min,x_max,y_max):
    print(pos[0],pos[1],x_min,y_min,x_max,y_max)
    x_match =(x_min < pos[0] <  x_max)
    y_match = (y_min < pos[1] <  y_max)
    if x_match and y_match:
        return True
    else:
        return False
###################初始化###################
pygame.init()    # 啟動 Pygame
width = 640 #設定視窗寬度
height = 320


###################設定文字#####################
typeface = pygame.font.get_default_font()
font = pygame.font.Font(typeface,24)
title = font.render("start",True,(0,0,0))
tit_w = title.get_width()
tit_h = title.get_height()
###################建立視窗及物件###################
# 設定視窗大小
screen = pygame.display.set_mode((width,height))
# 設定視窗標題
pygame.display.set_caption("My game")
###################建立畫布##################
#建立畫布
bg = pygame.Surface((width,height))
# 畫布為白色(R,G,B)
bg.fill((255,255,255))
###################循環偵測##################
paint = False # 畫布狀態
while True:
    screen.blit(bg,(0,0)) # 繪製畫布於視窗左上角
    mouse_pot = pygame.mouse.get_pos()
    # print(mouse_pot)
    for event in pygame.event.get():
        if event.type == pygame.QUIT: #如果吃下[x]就選出 # 使用者按關閉鈕
            sys.exit() #離開遊戲
        if event.type == pygame.MOUSEBUTTONDOWN:  # 偵測滑鼠按下
            if check_click(mouse_pot,int(0),int(0),tit_w,tit_h):
                paint = not paint
            print("clickll")  
            # print(pygame.mouse.get_pos())
    if paint:
        pygame.draw.circle(bg,(0,0,255),(200,100),30,0)
        pygame.draw.circle(bg,(0,0,255),(400,100),30,0)
        pygame.draw.rect(bg,(0,255,0),[270,130,60,40],5)
        pygame.draw.ellipse(bg,(255,0,0),[130,160,60,35],5)
        pygame.draw.ellipse(bg,(255,0,0),[400,160,60,35],5)
        pygame.draw.line(bg,(255,0,255),(280,220),(320,220))
    else:
        bg.fill('WHITE')
        screen.blit(title,(0,0))
    pygame.display.update() 
    bg.blit(title,(0,0))
    pygame.display.update()
    #繪製畫布於視窗左上角
    screen.blit(bg,(0,0))
    screen.blit(title,(0,0))
    #更新視窗
    pygame.display.update()
    ##################繪製畫布####################
    # pygame.draw.circle(bg, (0, 0, 255), (200, 100), 30, 0)
    # pygame.draw.rect(bg,(0,255,0),[270,130,60,40],5)
    # pygame.draw.ellipse(bg, (255, 0, 0), [130, 160, 60, 35], 5)
    # pygame.draw.line(bg, (255, 0, 245), (280, 220), (320, 220), 3)
    # pygame.draw.polygon(bg, (100, 200, 45), [[100, 100], [0, 200], [200, 200]], 0)
    # pygame.draw.arc(bg, (255, 10, 0), [100, 100, 100, 50], math.radians(180), math.radians(0), 2)
    # pygame.mouse.get_pos()
